### PR TITLE
Test application without config map

### PR DESCRIPTION
**Pull request by SlavoKrupa**
Merge when implemented.
Close it if "mission" has changed.

### CODE REVIEW

**Comment by cescoffier** [comment]
Yes, it's not implemented yet.

**Comment by cescoffier** [comment]
It's going to be a bit more tricky to implement than expected, as the deletion of the config map do NOT trigger a config change (it should, that's a bug in the vertx config map support).

Unfortunately, this require a new release of vertx-config. 3.4.2 is going to be released end of May.

**Comment by cescoffier** [comment]
I've found a way to turn around the issue until we fix it in vertx-config.

**Comment by SlavoKrupa** [comment]
I was trying to implement it by myself and got blocked by similar issue. Hence, I submitted just test.
Thanks for fix 👍

**Comment by cescoffier** [comment]
@SlavoKrupa The underlying issue is: https://github.com/vert-x3/vertx-config/issues/7

**Comment by cescoffier** [comment]
@SlavoKrupa vert-x3/vertx-config#7 has been fixed, I've pushed a branch named "vertx-3.4.2-SNAPSHOT" removing the work around.

**Pull request merged**
